POST http://localhost:5000/api/getendmessages HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhmNDMyMDRhMTc5MTVlOGJlN2NjZDdjYjI2NGRmNmVhMzgzYzQ5YWIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbWVldC1hLWRpbWUiLCJhdWQiOiJtZWV0LWEtZGltZSIsImF1dGhfdGltZSI6MTYyNjIwMzc1NiwidXNlcl9pZCI6ImI2cXVyWFREdlROd2lGRzd6MlJjM0VNYXZjQTIiLCJzdWIiOiJiNnF1clhURHZUTndpRkc3ejJSYzNFTWF2Y0EyIiwiaWF0IjoxNjI2MjAzNzU2LCJleHAiOjE2MjYyMDczNTYsImVtYWlsIjoibHVpdmFkZXIyMDAwQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImx1aXZhZGVyMjAwMEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.bIZzNn-iWLN-PzQy2R_xvAN5xynimKYsCSWLmRue5MC_7HVIWeBRr8DfpBQhIBqUC5G69_zC24jgxIQmyjEw_UX1-mHJ22SEgySnlVQPKXKTkHE1VGkhraGpaC-oVJ07mplzZXh86DJDch2gxLl1psKdsC09QH3eQQaTVUz_KjdJ2DOkEVt62aKvW55i-H9milFl0Q3EUiRZmxX5zaL5M6O8zDKJKlS5sHG6ZfbSDcJAoEebZAk_CyDl2JLBC-LVLyoJ71I5I5FIzpcYU4OdwP0y9sKCC-i4prCsDTGh0ZT29H-AxLBCbZtMN6qo5W2w_o3alSe2IqI4fZP760Igpw

{ 
    "user_uid": "b6qurXTDvTNwiFG7z2Rc3EMavcA2", "match_uid": "NZGL23QxStfOT5CutWX4B2MzfUG3" 
}